<?php

require __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

$keepTitles = [
    "RICOH AFICIO MP 3352",
    "RICOH AFICIO MP 4002",
    "RICOH AFICIO MP 5002",
    "RICOH MP 301 SPF",
    "RICOH MP 3054",
    "RICOH MP 3055",
    "RICOH MP 3554",
    "RICOH MPC 6003",
    "AVP CF400 (BK)",
    "AVP Q5951A/52A/53A (C/M/Y)",
    "AVP Q5950A (BK)",
    "AVP CE251A/52A/53A (C/M/Y)",
    "AVP CE250A (BK)",
    "AVP CE3 90A",
    "AVP 43X",
    "AVP 29X",
    "AVP 16A (309)",
    "AVP 55A",
    "AVP 87A",
    "AVP 26A",
    "AVP 49A",
    "AVP 80A",
    "AVP 85A",
    "AVP 12A",
    "AVP 05A",
    "AVP 17A",
    "AVP 51A",
    "AVP 151A",
    "AVP 76A",
    "AVP 283A",
    "AVP CF214A",
    "AVP CF351A/52A/53A (C/M/Y)",
    "AVP CF350A (BK)",
    "AVP CF211A/12A/13A (C/M/Y)",
    "AVP CF210A (BK)",
    "AVP CC531A/32A/33A (C/M/Y)",
    "AVP CC530 (BK)",
    "AVP CE321A/22A/23A (C/M/Y)",
    "AVP CE320A (BK)",
    "AVP CE411A/12A/13A (C/M/Y)",
    "AVP CE410A (BK)",
    "AVP CE311A/12A/13A (C/M/Y)",
    "AVP CE310A (BK)",
    "AVP CB541/42A/43A (C/M/Y)",
    "AVP CB540A (BK)",
    "AVP CE271A/72A/73A (C/M/Y)",
    "AVP CE270A (BK)",
    "AVP CF401A/2A/3A (C/M/Y)",
    "AVP DR 2025",
    "AVP DR 240B/ 240Y/ 240C/ 240M",
    "AVP TN 240B/ 240(Y/C/M)",
    "AVP DR-2255",
    "AVP TN-2280",
    "AVP DR-2125",
    "AVP TN-2130",
    "AVP TN-2025",
    "HP 67 Black Ink Cartridge",
    "HP 67 Tri-Color Ink Cartridge",
    "HP 680 Black Ink Cartridge",
    "HP 680 Color Ink Cartridge",
    "HP 954 Black Ink Cartridge",
    "HP GT53 Black Ink Bottle",
    "HP GT52 Color Ink Bottle",
    "Epson 003 Black Ink Bottle",
    "Epson 003 Cyan Ink Bottle",
    "Epson 003 Magenta Ink Bottle",
    "Epson 003 Yellow Ink Bottle",
    "Epson 664 Black Ink Bottle",
    "Epson 664 Cyan Ink Bottle",
    "Epson T673 Photo Black Ink Bottle",
    "OKI C332 Black Toner Cartridge",
    "OKI C332 Cyan Toner Cartridge",
    "OKI C332 Magenta Toner Cartridge",
    "OKI C332 Yellow Toner Cartridge",
    "OKI B412 Black Toner Cartridge",
    "OKI MC363 Black Toner Cartridge",
    "OKI MC363 Cyan Toner Cartridge",
    "Canon GI-790 Black Ink Bottle",
    "Canon GI-790 Cyan Ink Bottle",
    "Canon GI-790 Magenta Ink Bottle",
    "Canon GI-790 Yellow Ink Bottle",
    "Canon PG-745 Black Ink Cartridge",
    "Canon CL-746 Color Ink Cartridge",
    "Canon Cartridge 325 Toner",
    "Brother BT-D60 Black Ink Bottle",
    "Brother BT5000 Cyan Ink Bottle",
    "Brother BT5000 Magenta Ink Bottle",
    "Brother BT5000 Yellow Ink Bottle",
    "Brother TN-2385 Black Toner Cartridge",
    "Brother TN-261 Cyan Toner Cartridge",
    "Brother TN-261 Magenta Toner Cartridge",
    "Ricoh SP C250 Black Toner Cartridge",
    "Ricoh SP C250 Cyan Toner Cartridge",
    "Ricoh SP C250 Magenta Toner Cartridge",
    "Ricoh SP C250 Yellow Toner Cartridge",
    "Ricoh MP C3503 Black Toner Cartridge",
    "Ricoh MP C3503 Cyan Toner Cartridge",
    "Ricoh MP C3503 Magenta Toner Cartridge",
    "HP LaserJet Pro M404dn",
    "Canon imageCLASS LBP2900",
    "Brother HL-L2366DW",
    "Epson EcoTank L3250",
    "Canon PIXMA G3010",
    "HP Smart Tank 580",
    "Brother DCP-T720DW",
    "Canon imageCLASS MF3010",
    "HP LaserJet Pro MFP M428fdw",
    "Brother HL-L3270CDW",
    "Xerox Phaser 6510DN",
    "Pantum P2500W",
    "Epson EcoTank M3170",
    "HP Color LaserJet Pro M255dw",
    "Epson L3210",
    "Apple MacBook Air 13 M3",
    "Apple MacBook Pro 14 M4 Pro",
    "ASUS ROG Strix G16",
    "ASUS TUF Gaming A15",
    "Lenovo Legion Pro 5",
    "Lenovo IdeaPad Slim 5",
    "Dell XPS 13",
    "Dell Inspiron 15",
    "HP Victus 15",
    "HP Pavilion 14",
    "Acer Nitro V 15",
    "Acer Aspire 5",
    "MSI Katana 15",
    "MSI Modern 14",
    "Razer Blade 16",
    "Microsoft Surface Laptop 6",
    "LG Gram 16",
    "Huawei MateBook D 16",
    "Gigabyte G5 KF",
    "Samsung Galaxy Book4 Pro",
    "Apple iMac 24-inch M3",
    "Dell OptiPlex 7010 Tower",
    "HP ProDesk 400 G9",
    "Lenovo ThinkCentre M70t Gen 4",
    "ASUS ROG G22CH",
    "MSI MAG Infinite S3",
    "Acer Predator Orion 3000",
    "Lenovo Legion Tower 5",
    "HP OMEN 40L",
    "Dell Alienware Aurora R16",
    "ASUS ExpertCenter D7 Tower",
    "Apple Mac Mini M3",
    "Apple Mac Studio M3 Max",
    "Corsair Vengeance i7400",
    "CyberPowerPC Gamer Xtreme",
    "Gigabyte AORUS Model X",
    "Intel NUC 13 Pro",
    "Fujitsu ESPRIMO D7012",
    "Huawei MateStation S",
    "Samsung All-in-One Pro",
    "LG UltraGear G6 27” 300Hz",
    "LG UltraGear 27G610A-B",
    "ASUS ProArt PA248QV",
    "MSI Optix G241",
    "MSI Optix MAG241",
    "Acer Predator XB273U",
    "Samsung LF22T350FHEXXV",
    "Philips 276B1",
    "ViewSonic VG3820C",
    "LG UltraGear 24GN60R-B",
    "Corsair Vengeance LPX DDR4",
    "Kingston FURY Beast DDR5",
    "G.SKILL Trident Z5 Neo RGB DDR5",
    "Crucial DDR5 UDIMM",
    "Corsair Vengeance RGB DDR5",
    "G.SKILL Ripjaws V DDR4",
    "Crucial Laptop DDR5 SO-DIMM",
    "Corsair Dominator Platinum RGB DDR5",
    "TeamGroup T-Force Delta RGB DDR5",
    "Samsung DDR5 Desktop RAM",
    "Samsung 990 PRO 1TB NVMe SSD",
    "WD Black SN850X SSD",
    "Crucial P3 Plus NVMe SSD",
    "Kingston NV2 NVMe SSD",
    "Samsung 870 EVO SATA SSD",
    "Seagate BarraCuda HDD",
    "WD Blue HDD",
    "Toshiba P300 HDD",
    "Seagate IronWolf NAS HDD",
    "WD Purple Surveillance HDD",
    "ASUS ROG Maximus Z790 Hero",
    "GIGABYTE Z790 AORUS Elite AX",
    "MSI MAG X870 TOMAHAWK WIFI",
    "ASUS TUF Gaming B650-PLUS WIFI",
    "MSI B650 Gaming Plus WIFI",
    "ASRock B650M-HDV/M.2",
    "GIGABYTE X870E AORUS MASTER",
    "ASUS PRIME H610M-K D4",
    "MSI PRO B760M-A WIFI",
    "ASUS ROG Strix B550-F Gaming WIFI II",
    "Intel Core i9-14900K",
    "Intel Core i7-14700K",
    "Intel Core i5-14600K",
    "AMD Ryzen 9 9950X",
    "AMD Ryzen 7 9800X3D",
    "AMD Ryzen 5 9600X",
    "Intel Core i3-14100F",
    "AMD Ryzen 7 7800X3D",
    "Intel Core Ultra 7 265K",
    "AMD Ryzen 5 5600",
    "Logitech G Pro X Gaming Headset",
    "HyperX Cloud II",
    "Razer BlackShark V2",
    "SteelSeries Arctis Nova 7 Wireless",
    "Sony WH-1000XM5",
    "Bose QuietComfort Ultra Headphones",
    "JBL Quantum 100",
    "Corsair HS80 RGB Wireless",
    "Sennheiser HD 450BT",
    "ASUS ROG Delta S",
    "TP-Link Archer AX55",
    "ASUS RT-AX58U",
    "TP-Link Deco X20",
    "ASUS TUF Gaming AX4200",
    "Xiaomi Router AX3000T",
    "Netgear Nighthawk AX12 RAX120",
    "TP-Link Archer C6",
    "ASUS RT-AX86U Pro",
    "Huawei AX3 Quad-Core",
    "Linksys MR7350",
    "Corsair RM750x",
    "Cooler Master MWE Gold 750 V2",
    "ASUS ROG Strix 850G",
    "MSI MAG A650BN",
    "Seasonic Focus GX-750",
    "Corsair CV650",
    "Gigabyte UD750GM",
    "Thermaltake Toughpower GF A3 850W",
    "DeepCool PK650D",
    "EVGA SuperNOVA 850 G6",
    "Logitech G Pro X TKL Lightspeed",
    "Razer Huntsman V2",
    "Corsair K100 RGB",
    "Logitech MX Keys S",
    "Keychron K2 Wireless Mechanical Keyboard",
    "SteelSeries Apex Pro TKL",
    "ASUS ROG Azoth",
    "Dell KB216 Multimedia Keyboard",
    "HyperX Alloy Origins Core",
    "Logitech G213 Prodigy",
    "Logitech G Pro X Superlight 2",
    "Razer Viper V3 Pro",
    "Logitech G502 X Lightspeed",
    "Logitech MX Master 3S",
    "Razer DeathAdder V3 Pro",
    "Logitech M720 Triathlon",
    "SteelSeries Rival 3 Wireless",
    "ASUS TUF Gaming M4 Wireless",
    "Corsair Ironclaw RGB Wireless",
    "Microsoft Bluetooth Ergonomic Mouse",
    "NVIDIA GeForce RTX 4060",
    "NVIDIA GeForce RTX 4070 SUPER",
    "NVIDIA GeForce RTX 4080 SUPER",
    "NVIDIA GeForce RTX 3060",
    "NVIDIA GeForce RTX 4090",
    "Ronald Jack RJ550A",
    "ZKTeco MB20",
    "Hikvision DS-K1T804MF",
    "Suprema BioStation 3",
    "Dahua DHI-ASI1212F",
    "Fellowes Powershred 79Ci",
    "Bonsaii C149-C",
    "Aurora AS890C",
    "Rexel Momentum X410",
    "HSM Shredstar X10",
    "Epson TM-T82III",
    "Xprinter XP-Q200II",
    "Rongta RP326",
    "Star Micronics TSP143III",
    "Bixolon SRP-350III",
    "Epson Perfection V39 II",
    "Canon CanoScan LiDE 400",
    "Fujitsu fi-8170",
    "Brother ADS-2200",
    "HP ScanJet Pro 2600 f1",
    "Epson EB-X06",
    "BenQ MX560",
    "ViewSonic PA503X",
    "Optoma EH412",
    "Xiaomi Smart Projector 2",
    "TP-Link Archer AX55",
    "ASUS RT-AX52",
    "TP-Link Archer C54",
    "NETGEAR Nighthawk RAX50",
    "Mercusys MW302R",
    "UGREEN Cat6 Ethernet Cable",
    "Vention Cat6 Ethernet Cable",
    "AMP CAT6 UTP Cable",
    "Dintek CAT6 Patch Cord",
    "Belkin Cat6 Ethernet Cable",
    "TP-Link TL-SG108",
    "TP-Link TL-SG1005D",
    "Netgear ProSafe GS105",
    "Cisco CBS110-8T-D",
    "D-Link DGS-108"
];

$keepTitles = array_map('trim', $keepTitles);

// Get IDs of products to keep
$keepIds = DB::table('product')->whereIn('title', $keepTitles)->pluck('id')->toArray();

// Find IDs of products to delete
$deleteIds = DB::table('product')->whereNotIn('id', $keepIds)->pluck('id')->toArray();

if (empty($deleteIds)) {
    echo "No products to delete.\n";
    exit;
}

echo "Deleting " . count($deleteIds) . " products...\n";

// Delete related variants first
DB::table('variant')->whereIn('product_id', $deleteIds)->delete();

// Delete the products
$deletedCount = DB::table('product')->whereIn('id', $deleteIds)->delete();

echo "Successfully deleted $deletedCount products.\n";
