<?php
require __DIR__ . '/../vendor/autoload.php';
$app = require_once __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

$data = [
    "LG UltraGear G6 27” 300Hz" => "Màn hình chơi game QHD 27 inch cao cấp được thiết kế cho thể thao điện tử và thiết lập chơi game hiệu suất cao. Có tấm nền IPS 2560×1440 với tốc độ làm mới 300Hz cực nhanh và thời gian phản hồi 1ms để chơi game mượt mà, không bị mờ. Hỗ trợ kết nối HDR, AMD FreeSync Premium, HDMI và DisplayPort, tái tạo màu sắc sống động và hiệu suất chơi game cạnh tranh siêu nhạy. Lý tưởng cho môi trường chơi game FPS, MOBA và AAA.",
    "LG UltraGear 27G610A-B" => "Màn hình chơi game QHD IPS 27 inch hiệu suất cao có tốc độ làm mới 200Hz, thời gian phản hồi 1ms, hỗ trợ HDR10 và công nghệ AMD FreeSync. Mang lại độ chính xác màu sắc sống động, hình ảnh mượt mà và hiệu suất chơi game có độ trễ thấp. Thiết kế viền mỏng hiện đại phù hợp với các trạm chơi game và không gian làm việc của người sáng tạo. Kết nối bao gồm HDMI và DisplayPort.",
    "ASUS ProArt PA248QV" => "Màn hình WUXGA 24,1 inch cấp độ chuyên nghiệp được thiết kế cho người sáng tạo, nhà thiết kế và biên tập viên. Được trang bị công nghệ IPS, độ phân giải 1920×1200, độ chính xác màu được hiệu chỉnh tại nhà máy, độ bao phủ 100% sRGB / Rec.709 và điều chỉnh chân đế tiện dụng. Có tính năng Adaptive-Sync, HDMI, DisplayPort, bộ chia USB và tái tạo màu sắc chính xác cho quy trình làm việc sáng tạo chuyên nghiệp.",
    "MSI Optix G241" => "Màn hình chơi game Full HD 23,8 inch phổ biến với tấm nền IPS, tốc độ làm mới 144Hz và thời gian phản hồi 1ms. Được thiết kế để chơi game cạnh tranh với hình ảnh mượt mà, làm mờ chuyển động thấp và góc nhìn rộng. Hỗ trợ AMD FreeSync và công nghệ gam màu rộng cho trải nghiệm chơi game và đa phương tiện đắm chìm.",
    "MSI Optix MAG241" => "Màn hình chơi game Full HD 24 inch cong có công nghệ tấm nền VA, tốc độ làm mới 144Hz và thời gian phản hồi 1ms. Được thiết kế để chơi game đắm chìm với độ tương phản nâng cao, đắm chìm trên màn hình cong và hiệu suất chơi trò chơi nhạy bén. Hỗ trợ AMD FreeSync và kiểu dáng tập trung vào chơi game.",
    "Acer Predator XB273U" => "Màn hình chơi game QHD 27 inch cao cấp với tấm nền IPS, tốc độ làm mới 165Hz (ép xung 170Hz), thời gian phản hồi 1ms, khả năng tương thích NVIDIA G-SYNC và hỗ trợ HDR400. Cung cấp hình ảnh chơi game cao cấp, hiệu suất độ trễ thấp và độ chính xác màu vượt trội cho các tác vụ chơi game và sản xuất sáng tạo.",
    "Samsung LF22T350FHEXXV" => "Màn hình IPS Full HD 21,5 inch đáng tin cậy được thiết kế để làm việc văn phòng, học tập và giải trí tại nhà. Có tốc độ làm mới 75Hz, hỗ trợ AMD FreeSync, thiết kế hiện đại không viền, góc nhìn thoải mái và kết nối HDMI. Tuyệt vời cho các máy trạm tập trung vào năng suất và sử dụng hàng ngày.",
    "Philips 276B1" => "Màn hình QHD IPS 27 inch hướng đến năng suất với hỗ trợ đế cắm USB-C, tốc độ làm mới 75Hz, công nghệ Flicker-Free và chức năng không gian làm việc tiện dụng. Mang lại chất lượng hình ảnh sắc nét và quản lý cáp đơn giản cho môi trường văn phòng chuyên nghiệp và quy trình làm việc đa nhiệm.",
    "ViewSonic VG3820C" => "Màn hình siêu rộng cong lớn 38 inch có độ phân giải 3840×1600, kết nối USB-C, tốc độ làm mới 75Hz, loa tích hợp và khả năng đa nhiệm đắm chìm. Lý tưởng cho các chuyên gia kinh doanh, nhà sáng tạo, nhà phân tích tài chính và máy trạm đòi hỏi năng suất cao.",
    "LG UltraGear 24GN60R-B" => "Màn hình chơi game cạnh tranh với màn hình IPS Full HD 23,8 inch, tốc độ làm mới 144Hz, thời gian phản hồi 1ms, hỗ trợ FreeSync Premium và độ phủ màu 99% sRGB. Kết hợp tốc độ ở cấp độ thể thao điện tử với hiệu suất màu sắc tuyệt vời để thiết lập chơi game, phát trực tuyến và giải trí.",
    "Corsair Vengeance LPX DDR4" => "RAM máy tính để bàn hiệu suất cao được thiết kế cho PC chơi game và hệ thống năng suất. Có công nghệ bộ nhớ DDR4, tùy chọn tốc độ 3200MHz–3600MHz, bộ tản nhiệt bằng nhôm cấu hình thấp, hỗ trợ ép xung được tối ưu hóa, hiệu suất độ trễ thấp và khả năng tương thích Intel XMP. Phổ biến trên toàn thế giới về độ tin cậy, giá cả phải chăng và hiệu suất chơi game ổn định. Lý tưởng cho các bản dựng chơi game, máy trạm văn phòng và PC tạo nội dung.",
    "Kingston FURY Beast DDR5" => "Bộ nhớ chơi game DDR5 cao cấp có tốc độ lên đến 6000MHz, kiến trúc độ trễ thấp, hỗ trợ Intel XMP 3.0, bộ tản nhiệt màu đen thời trang và hiệu suất được tối ưu hóa cho các nền tảng Intel và AMD hiện đại. Được sử dụng rộng rãi trong các hệ thống chơi game và năng suất cao cấp trên toàn thế giới.",
    "G.SKILL Trident Z5 Neo RGB DDR5" => "RAM đam mê cao cấp được thiết kế cho nền tảng AMD EXPO. Có tốc độ DDR5 6000MHz, ánh sáng RGB, bộ tản nhiệt bằng nhôm, điều chỉnh độ trễ thấp, tối ưu hóa kênh đôi và hiệu suất ép xung cao cấp. Một trong những dòng RAM chơi game được công nhận nhất trên toàn cầu.",
    "Crucial DDR5 UDIMM" => "Bộ nhớ máy tính DDR5 đáng tin cậy được thiết kế cho hiệu suất máy trạm, chơi game và đa nhiệm chuyên nghiệp. Có tốc độ 4800MHz–5600MHz, cải thiện hiệu suất băng thông, tiêu thụ điện năng thấp hơn và khả năng tương thích tuyệt vời với bo mạch chủ thế hệ tiếp theo. Được tin cậy trên toàn cầu về sự ổn định lâu dài và tính linh hoạt trong việc nâng cấp.",
    "Corsair Vengeance RGB DDR5" => "RAM chơi game RGB tiên tiến có hệ thống chiếu sáng có thể tùy chỉnh, tốc độ DDR5 6000MHz, hỗ trợ Intel XMP, bộ tản nhiệt bằng nhôm cao cấp và điều chỉnh hiệu suất tối ưu cho hệ thống chơi game và sáng tạo. Mang lại cả tính thẩm mỹ và khả năng phản hồi tốc độ cao.",
    "G.SKILL Ripjaws V DDR4" => "RAM chơi game DDR4 phổ biến với các tùy chọn tốc độ 3200MHz–3600MHz, thiết kế tản nhiệt cấu hình thấp, hỗ trợ Intel XMP và khả năng ép xung mạnh mẽ. Thường được khuyên dùng cho PC chơi game do tỷ lệ giá trên hiệu suất tuyệt vời và khả năng tương thích rộng của bo mạch chủ.",
    "Crucial Laptop DDR5 SO-DIMM" => "Mô-đun bộ nhớ máy tính xách tay DDR5 nhỏ gọn được thiết kế để nâng cấp máy tính xách tay và máy trạm di động. Có tốc độ 4800MHz–5600MHz, cải thiện hiệu suất năng lượng, khả năng đa nhiệm nhanh hơn và hiệu suất máy tính xách tay ổn định. Thích hợp cho máy tính xách tay chơi game, máy tính xách tay sáng tạo và máy tính xách tay văn phòng.",
    "Corsair Dominator Platinum RGB DDR5" => "RAM sang trọng được thiết kế cho máy tính chơi game và người sáng tạo cao cấp. Có hiệu suất tần số cao DDR5, công nghệ làm mát DHX đã được cấp bằng sáng chế, ánh sáng RGB có thể tùy chỉnh, kết cấu nhôm cao cấp và khả năng ép xung ưu tú. Được công nhận rộng rãi trong số những người đam mê PC cao cấp.",
    "TeamGroup T-Force Delta RGB DDR5" => "RAM chơi game thời trang với ánh sáng RGB mạnh mẽ, kiến trúc DDR5 tốc độ cao, tản nhiệt bằng nhôm, hỗ trợ Intel XMP và tính thẩm mỹ thiết kế tập trung vào chơi game. Phổ biến đối với các nhà xây dựng PC chơi game đang tìm kiếm cả hiệu suất và tùy chỉnh hình ảnh.",
    "Samsung DDR5 Desktop RAM" => "Mô-đun bộ nhớ DDR5 hàng đầu trong ngành do Samsung sản xuất trực tiếp. Tính năng quản lý năng lượng hiệu quả, truyền dữ liệu tốc độ cao, độ tin cậy lâu dài tuyệt vời và khả năng tương thích hệ thống rộng. Thường được sử dụng trong PC doanh nghiệp, máy trạm chuyên nghiệp và hệ thống chơi game trên toàn thế giới.",
    "Samsung 990 PRO 1TB NVMe SSD" => "SSD PCIe 4.0 NVMe M.2 cao cấp được thiết kế cho PC chơi game cao cấp, máy trạm dành cho người sáng tạo và nâng cấp PlayStation 5. Có tốc độ đọc/ghi tuần tự lên đến 7450MB/giây và 6900MB/giây, công nghệ Samsung V-NAND, điều khiển nhiệt tiên tiến, hiệu quả năng lượng vượt trội, giao diện PCIe Gen4 x4 và hệ số hình thức M.2 2280. Một trong những ổ SSD đam mê được công nhận nhất thế giới dành cho hệ thống chơi game và năng suất.",
    "WD Black SN850X SSD" => "SSD PCIe Gen4 NVMe hiệu suất cao được thiết kế để chơi game cạnh tranh và khả năng phản hồi hệ thống cực nhanh. Có tốc độ đọc lên đến 7300MB/s, tản nhiệt tùy chọn, chế độ tối ưu hóa chơi game, hỗ trợ phần mềm WD Dashboard và quản lý nhiệt cao cấp cho khối lượng công việc tốc độ cao bền vững.",
    "Crucial P3 Plus NVMe SSD" => "SSD PCIe Gen4 NVMe giá cả phải chăng mang đến hiệu suất mạnh mẽ hàng ngày để chơi game, năng suất văn phòng và nâng cấp máy trạm. Có tốc độ đọc lên đến 5000MB/s, hệ số dạng M.2 2280, công nghệ Micron Advanced 3D NAND, tiêu thụ điện năng thấp và tỷ lệ giá trên hiệu suất tuyệt vời.",
    "Kingston NV2 NVMe SSD" => "SSD PCIe 4.0 NVMe cấp thấp được sử dụng rộng rãi với thiết kế M.2 nhỏ gọn, hoạt động nhiệt hiệu quả, hiệu suất đáng tin cậy và tốc độ khởi động nhanh. Thích hợp cho PC chơi game, máy tính xách tay và hệ thống văn phòng yêu cầu nâng cấp SSD giá cả phải chăng và cải thiện hiệu suất đa nhiệm.",
    "Samsung 870 EVO SATA SSD" => "Một trong những ổ SSD SATA đáng tin cậy nhất thế giới dành cho máy tính để bàn và máy tính xách tay. Có giao diện SATA III, tốc độ đọc lên đến 560MB/giây, công nghệ bộ nhớ Samsung V-NAND, độ bền nâng cao, khả năng tương thích hệ thống rộng rãi và hiệu suất tính toán hàng ngày đáng tin cậy.",
    "Seagate BarraCuda HDD" => "Ổ cứng máy tính để bàn phổ biến trên toàn cầu được thiết kế cho bộ nhớ lớn, thư viện trò chơi, tệp đa phương tiện và hệ thống văn phòng. Có giao diện SATA 6Gb/s, tốc độ quay 7200RPM, dung lượng lưu trữ lớn và độ tin cậy lưu trữ lâu dài đáng tin cậy cho máy tính để bàn.",
    "WD Blue HDD" => "Ổ cứng chính đáng tin cậy được thiết kế cho máy tính để bàn hàng ngày, hệ thống văn phòng và môi trường lưu trữ gia đình. Có giao diện SATA III, hoạt động ổn định, tiêu thụ điện năng thấp, khả năng tương thích rộng rãi với máy tính để bàn và hiệu suất lưu trữ lâu dài đáng tin cậy.",
    "Toshiba P300 HDD" => "Ổ cứng máy tính để bàn dung lượng cao được thiết kế cho hệ thống chơi game, chỉnh sửa đa phương tiện và lưu trữ tệp chuyên nghiệp. Có tốc độ quay 7200RPM, bộ nhớ đệm tích hợp lớn, giao diện SATA và hiệu suất lưu trữ dung lượng cao ổn định cho người dùng khó tính.",
    "Seagate IronWolf NAS HDD" => "Ổ cứng được tối ưu hóa cho NAS được xây dựng để hoạt động 24/7 trong các máy chủ gia đình và hệ thống NAS doanh nghiệp. Tính năng tối ưu hóa chương trình cơ sở AgileArray, chống rung, khả năng tương thích RAID, xếp hạng khối lượng công việc cao và hiệu suất đa ổ đĩa đáng tin cậy cho các hệ thống lưu trữ chuyên nghiệp.",
    "WD Purple Surveillance HDD" => "Ổ cứng giám sát chuyên dụng được thiết kế cho camera quan sát và hệ thống ghi âm an ninh. Có công nghệ AllFrame, quay video liên tục được tối ưu hóa, độ bền nâng cao để hoạt động 24/7 và khả năng tương thích với hệ thống giám sát DVR và NVR.",
    "ASUS ROG Maximus Z790 Hero" => "Bo mạch chủ chơi game cao cấp cao cấp được thiết kế cho các hệ thống đam mê Intel. Có chipset Intel Z790, ổ cắm LGA1700, hỗ trợ bộ nhớ DDR5 lên đến 192GB, mở rộng PCIe 5.0, Wi-Fi 6E, nhiều khe cắm M.2 NVMe, tản nhiệt VRM cao cấp, đèn RGB, kết nối Thunderbolt và khả năng ép xung nâng cao. Được công nhận rộng rãi trong giới game thủ, streamer và nhà lắp ráp PC chuyên nghiệp trên toàn thế giới.",
    "GIGABYTE Z790 AORUS Elite AX" => "Bo mạch chủ chơi game Intel phổ biến có chipset Z790, ổ cắm LGA1700, hỗ trợ DDR5, PCIe 5.0, Wi-Fi 6E, Ethernet 2.5Gb, nhiều khe cắm SSD M.2, thiết kế tản nhiệt VRM tiên tiến và tối ưu hóa BIOS tập trung vào chơi game. Rất khuyến khích cho các bản dựng máy trạm và chơi game hiệu suất cao.",
    "MSI MAG X870 TOMAHAWK WIFI" => "Bo mạch chủ chơi game AMD AM5 hiện đại được thiết kế cho bộ vi xử lý Ryzen. Có chipset AMD X870, hỗ trợ DDR5, PCIe 5.0, Wi-Fi 7, Bluetooth 5.4, khe cắm PCIe được gia cố, tản nhiệt tiên tiến và kết nối USB tốc độ cao. Tuyệt vời cho hệ thống người sáng tạo và chơi game thế hệ tiếp theo.",
    "ASUS TUF Gaming B650-PLUS WIFI" => "Bo mạch chủ AMD AM5 bền bỉ được thiết kế để chơi game phổ thông và độ tin cậy lâu dài. Có chipset B650, hỗ trợ bộ nhớ DDR5, hỗ trợ PCIe 5.0 M.2, các thành phần cấp quân sự, Wi-Fi 6, giải pháp làm mát toàn diện và khe cắm PCIe được gia cố. Phổ biến đối với các game thủ tìm kiếm độ tin cậy và giá trị.",
    "MSI B650 Gaming Plus WIFI" => "Bo mạch chủ AMD tầm trung có socket AM5, hỗ trợ bộ nhớ DDR5, tương thích PCIe 4.0/5.0, hỗ trợ Wi-Fi, thiết kế tản nhiệt mở rộng, kết nối USB tốc độ cao và hiệu suất tản nhiệt hướng đến chơi game. Được sử dụng rộng rãi trong các bản dựng PC chơi game Ryzen trên toàn thế giới.",
    "ASRock B650M-HDV/M.2" => "Bo mạch chủ AMD AM5 micro-ATX giá cả phải chăng và đáng tin cậy được thiết kế cho máy tính văn phòng và chơi game giá rẻ. Có hỗ trợ DDR5, bộ nhớ PCIe 4.0 M.2, hệ thống cung cấp năng lượng bền bỉ, đầu ra HDMI/DisplayPort và thiết kế micro-ATX nhỏ gọn phù hợp với các bản dựng nhỏ hơn.",
    "GIGABYTE X870E AORUS MASTER" => "Bo mạch chủ AMD đẳng cấp dành cho người đam mê có chipset X870E, socket AM5, hỗ trợ GPU PCIe 5.0 và SSD, kiến trúc VRM cao cấp, Wi-Fi 7, mạng tốc độ cao, hệ thống tản nhiệt tiên tiến và nhiều khe cắm lưu trữ NVMe. Được thiết kế để chơi game cực đỉnh và hiệu suất máy trạm chuyên nghiệp.",
    "ASUS PRIME H610M-K D4" => "Bo mạch chủ Intel cấp thấp được thiết kế cho PC văn phòng và hệ thống máy tính để bàn giá cả phải chăng. Có chipset Intel H610, ổ cắm LGA1700, hỗ trợ bộ nhớ DDR4, khả năng tương thích PCIe 4.0, hỗ trợ M.2 NVMe và hiệu suất tính toán ổn định hàng ngày. Thường được sử dụng trong PC doanh nghiệp và văn phòng tại nhà.",
    "MSI PRO B760M-A WIFI" => "Bo mạch chủ Intel tập trung vào doanh nghiệp và năng suất hỗ trợ bộ xử lý Intel thế hệ thứ 12/13/14. Có hỗ trợ bộ nhớ DDR5, PCIe 4.0, kết nối Wi-Fi, thiết kế tản nhiệt cấp độ chuyên nghiệp, hỗ trợ SSD M.2 và cung cấp năng lượng ổn định cho khối lượng công việc văn phòng và người sáng tạo.",
    "ASUS ROG Strix B550-F Gaming WIFI II" => "Một trong những bo mạch chủ chơi game AMD AM4 phổ biến nhất thế giới. Có chipset AMD B550, hỗ trợ PCIe 4.0, khả năng tương thích bộ nhớ DDR4, Wi-Fi 6, âm thanh SupremeFX cao cấp, khe cắm PCIe được gia cố, ánh sáng RGB và tản nhiệt VRM mạnh mẽ cho các hệ thống chơi game và phát trực tuyến.",
    "Intel Core i9-14900K" => "Bộ xử lý máy tính để bàn hàng đầu của Intel được thiết kế cho những người đam mê chơi game, phát trực tuyến và khối lượng công việc của người sáng tạo chuyên nghiệp. Có 24 lõi (8 Hiệu suất + 16 lõi hiệu quả), 32 luồng, xung nhịp tăng lên đến 6.0GHz, khả năng tương thích với ổ cắm Intel LGA1700, hỗ trợ bộ nhớ DDR5/DDR4, hỗ trợ PCIe 5.0, Intel UHD Graphics 770 tích hợp, khả năng ép xung được mở khóa và kiến trúc lai tiên tiến cho hiệu suất chơi game và đa nhiệm cực cao.",
    "Intel Core i7-14700K" => "Bộ xử lý năng suất và chơi game hiệu suất cao với 20 lõi (8P + 12E), 28 luồng, tốc độ tăng lên đến 5,6GHz, kiến trúc lai Intel, khả năng tương thích DDR5/DDR4, hỗ trợ PCIe 5.0, đồ họa tích hợp và hệ số nhân mở khóa để ép xung. Được sử dụng rộng rãi trong PC chơi game và hệ thống máy trạm trên toàn cầu.",
    "Intel Core i5-14600K" => "Bộ xử lý chơi game phổ biến cung cấp tỷ lệ giá trên hiệu suất tuyệt vời. Có 14 lõi (6P + 8E), 20 luồng, xung nhịp tăng lên đến 5.3GHz, Intel UHD Graphics 770, hỗ trợ PCIe 5.0, khả năng tương thích DDR5 và khả năng chơi game và đa nhiệm mạnh mẽ cho PC chơi game hiện đại.",
    "AMD Ryzen 9 9950X" => "Bộ xử lý máy tính để bàn AMD cao cấp được xây dựng để chơi game, kết xuất, khối lượng công việc AI và sáng tạo nội dung chuyên nghiệp cao cấp. Có 16 lõi, 32 luồng, kiến trúc Zen 5, tần số tăng trên 5.7GHz, khả năng tương thích nền tảng AM5, hỗ trợ DDR5, hỗ trợ PCIe 5.0 và hiệu suất năng lượng nâng cao cho các hệ thống máy tính để bàn thế hệ tiếp theo.",
    "AMD Ryzen 7 9800X3D" => "Bộ xử lý chơi game tiên tiến sử dụng công nghệ AMD 3D V-Cache cho hiệu suất chơi game ưu việt. Có 8 lõi, 16 luồng, tối ưu hóa bộ nhớ đệm L3 lớn, khả năng FPS chơi game cao, khả năng tương thích AM5, hỗ trợ bộ nhớ DDR5, hỗ trợ PCIe 5.0 và hiệu suất nhiệt tuyệt vời cho các bản dựng chơi game đam mê.",
    "AMD Ryzen 5 9600X" => "Bộ xử lý chơi game AMD chính thống mang lại hiệu suất đa lõi mạnh mẽ và khả năng phản hồi chơi game. Có 6 lõi, 12 luồng, kiến trúc Zen 5, khả năng tương thích với ổ cắm AM5, hỗ trợ DDR5, sẵn sàng PCIe 5.0 và mức tiêu thụ điện năng hiệu quả phù hợp cho PC chơi game và năng suất.",
    "Intel Core i3-14100F" => "Bộ xử lý chơi game để bàn cấp thấp giá cả phải chăng có 4 lõi, 8 luồng, tốc độ xung nhịp cao, khả năng tương thích với Intel LGA1700, hỗ trợ DDR4 / DDR5 và giá trị mạnh mẽ cho các hệ thống chơi game giá rẻ. Yêu cầu card đồ họa chuyên dụng do thiếu đồ họa tích hợp.",
    "AMD Ryzen 7 7800X3D" => "Một trong những CPU chơi game phổ biến nhất thế giới được biết đến với hiệu suất và hiệu suất chơi game vượt trội. Có 8 lõi, 16 luồng, công nghệ AMD 3D V-Cache, hỗ trợ ổ cắm AM5, khả năng tương thích DDR5, hỗ trợ PCIe 5.0 và hiệu suất FPS chơi game hàng đầu trong ngành.",
    "Intel Core Ultra 7 265K" => "Bộ xử lý máy tính để bàn Intel hiện đại tập trung vào AI có kiến trúc lõi lai tiên tiến, khả năng tăng tốc AI tích hợp, hỗ trợ DDR5, khả năng tương thích PCIe 5.0, hiệu quả được cải thiện, hiệu suất chơi game và năng suất mạnh mẽ cho khối lượng công việc điện toán máy tính để bàn thế hệ tiếp theo.",
    "AMD Ryzen 5 5600" => "Bộ xử lý AMD được mua rộng rãi mang lại khả năng chi trả và hiệu suất chơi game tuyệt vời. Có 6 lõi, 12 luồng, khả năng tương thích với socket AM4, hỗ trợ bộ nhớ DDR4, hỗ trợ PCIe 4.0, thiết kế tản nhiệt hiệu quả và hiệu suất chơi game mạnh mẽ cho các bản dựng máy tính để bàn chính thống và ngân sách trên toàn thế giới.",
    "Logitech G Pro X Gaming Headset" => "Tai nghe chơi game thể thao điện tử chuyên nghiệp được thiết kế cho các game thủ và streamer cạnh tranh. Có trình điều khiển PRO-G 50mm, Âm thanh vòm DTS Headphone: X 2.0, Blue VO có thể tháo rời! Công nghệ micrô CE, đệm tai bằng mút hoạt tính, kết cấu bằng nhôm và thép bền, card âm thanh bên ngoài USB và khả năng tương thích với PC, PlayStation, Xbox và Nintendo Switch.",
    "HyperX Cloud II" => "Một trong những tai nghe chơi game phổ biến nhất thế giới được biết đến với sự thoải mái và hiệu suất âm thanh sống động. Có trình điều khiển 53mm, âm thanh vòm ảo 7.1, micrô khử tiếng ồn có thể tháo rời, đệm tai bằng mút hoạt tính, độ bền của khung nhôm và khả năng tương thích đa nền tảng để chơi game và giao tiếp.",
    "Razer BlackShark V2" => "Tai nghe chơi game tập trung vào thể thao điện tử nhẹ có trình điều khiển TriForce Titanium 50mm, THX Spatial Audio, micrô HyperClear cardioid có thể tháo rời, đệm tai bằng mút hoạt tính, cách ly tiếng ồn thụ động tiên tiến và hỗ trợ card âm thanh USB cho môi trường chơi game cạnh tranh.",
    "SteelSeries Arctis Nova 7 Wireless" => "Tai nghe chơi game không dây cao cấp được thiết kế để chơi game, năng suất và giải trí. Có âm thanh không gian 360 °, micrô khử tiếng ồn được hỗ trợ bởi AI, kết nối không dây kép (2.4GHz + Bluetooth), thời lượng pin dài, thiết kế thoải mái nhẹ và khả năng tương thích đa nền tảng bao gồm PC, PlayStation và thiết bị di động.",
    "Sony WH-1000XM5" => "Tai nghe văn phòng và du lịch không dây hàng đầu trong ngành có tính năng khử tiếng ồn chủ động tiên tiến, chất lượng âm thanh cao cấp, thời lượng pin 30 giờ, điều khiển cảm ứng, ghép nối nhiều thiết bị, giảm tiếng ồn micrô dựa trên AI, sạc nhanh USB-C và tiện nghi công thái học nhẹ cho công việc văn phòng và giải trí.",
    "Bose QuietComfort Ultra Headphones" => "Tai nghe văn phòng và du lịch cao cấp được thiết kế để mang lại sự thoải mái đặc biệt và khử tiếng ồn chủ động. Có âm thanh không gian sống động, công nghệ ANC tiên tiến, điều chỉnh âm thanh có độ trung thực cao, kết nối không dây Bluetooth, thời lượng pin dài và thiết kế nhẹ sang trọng phù hợp cho mục đích sử dụng chuyên nghiệp và hàng ngày.",
    "JBL Quantum 100" => "Tai nghe chơi game giá cả phải chăng có âm thanh JBL QuantumSOUND Signature, micrô cần có thể tháo rời, thiết kế over-ear nhẹ, đệm tai bằng mút hoạt tính và khả năng tương thích với PC, PlayStation, Xbox, Nintendo Switch và các thiết bị chơi game di động.",
    "Corsair HS80 RGB Wireless" => "Tai nghe chơi game không dây hiệu suất cao có âm thanh không gian Dolby Atmos, kết nối không dây có độ trễ thấp, micrô đa hướng cấp phát sóng, ánh sáng RGB, bọt hoạt tính thoải mái, độ bền khung nhôm và thời lượng pin lên đến 20 giờ cho các phiên chơi game và phát trực tuyến.",
    "Sennheiser HD 450BT" => "Tai nghe văn phòng và giải trí không dây cung cấp khả năng khử tiếng ồn chủ động, âm thanh nổi chất lượng cao, kết nối Bluetooth 5.0, sạc USB-C, thiết kế nhẹ có thể gập lại, thời lượng pin dài và hỗ trợ trợ lý giọng nói và quy trình làm việc năng suất di động.",
    "ASUS ROG Delta S" => "Tai nghe chơi game cao cấp có công nghệ ESS 9281 Quad DAC, micrô khử tiếng ồn AI, ánh sáng RGB, thiết kế tiện dụng nhẹ, chứng nhận âm thanh độ phân giải cao, kết nối USB-C và hiệu suất âm thanh chơi game đắm chìm cho các thiết lập chơi game cạnh tranh và thông thường.",
    "TP-Link Archer AX55" => "Bộ định tuyến băng tần kép Wi-Fi 6 phổ biến được thiết kế để chơi game, phát trực tuyến và kết nối nhà thông minh. Có tốc độ không dây AX3000 lên đến 3000Mbps, hoạt động băng tần kép 2.4GHz và 5GHz, công nghệ OFDMA và MU-MIMO, bảo mật WPA3, cổng Gigabit Ethernet, kết nối USB 3.0 và vùng phủ sóng mạnh mẽ cho các ngôi nhà từ trung bình đến lớn.",
    "ASUS RT-AX58U" => "Bộ định tuyến Wi-Fi 6 được công nhận rộng rãi được thiết kế để chơi game và kết nối mạng gia đình tốc độ cao. Có hiệu suất không dây AX3000, bảo mật mạng AiProtection Pro, MU-MIMO, OFDMA, hỗ trợ băng tần kép, QoS thích ứng, khả năng tương thích AiMesh và kết nối Gigabit LAN/WAN cho hiệu suất độ trễ thấp ổn định.",
    "TP-Link Deco X20" => "Hệ thống Wi-Fi 6 lưới phổ biến cung cấp vùng phủ sóng không dây liền mạch cho toàn bộ ngôi nhà. Có tốc độ băng tần kép AX1800, công nghệ mạng lưới, kiểm soát của phụ huynh, bảo mật WPA3, chuyển vùng thông minh, hỗ trợ nhiều thiết bị được kết nối và quản lý dựa trên ứng dụng cho nhà thông minh hiện đại.",
    "ASUS TUF Gaming AX4200" => "Bộ định tuyến Wi-Fi 6 tập trung vào chơi game được thiết kế để chơi game có độ trễ thấp và kết nối tốc độ cao ổn định. Có tốc độ không dây AX4200, ưu tiên cổng chơi game, hỗ trợ AiMesh, thiết kế làm mát tiên tiến, QoS thích ứng, bảo mật WPA3 và khả năng xử lý đa thiết bị mạnh mẽ.",
    "Xiaomi Router AX3000T" => "Bộ định tuyến Wi-Fi 6 giá cả phải chăng mang lại hiệu suất không dây nhanh cho môi trường gia đình và văn phòng. Có tốc độ AX3000, kết nối băng tần kép, công nghệ MU-MIMO, hỗ trợ mạng lưới, cổng Gigabit Ethernet, thiết kế nhỏ gọn và giá trị tuyệt vời cho các thiết lập mạng chính thống.",
    "Netgear Nighthawk AX12 RAX120" => "Bộ định tuyến Wi-Fi 6 cao cấp được thiết kế cho những ngôi nhà lớn, chơi game và khối lượng công việc phát trực tuyến nặng. Có hiệu suất không dây AX6000, bộ xử lý lõi tứ mạnh mẽ, nhiều cổng Gigabit, định dạng chùm tia tiên tiến, kết nối USB 3.0 và khả năng xử lý thiết bị mở rộng cho các mạng đòi hỏi khắt khe.",
    "TP-Link Archer C6" => "Một trong những bộ định tuyến ngân sách được mua phổ biến nhất trên toàn thế giới. Có tốc độ không dây AC1200 băng tần kép, hỗ trợ MU-MIMO, bốn ăng-ten bên ngoài, chế độ điểm truy cập, cổng Gigabit và hiệu suất không dây ổn định phù hợp cho việc sử dụng internet gia đình và thiết lập văn phòng.",
    "ASUS RT-AX86U Pro" => "Bộ định tuyến chơi game cao cấp được thiết kế cho thể thao điện tử, phát trực tuyến và hiệu suất internet tốc độ cao. Có tốc độ Wi-Fi 6 AX5700, chế độ chơi game di động, điều khiển QoS nâng cao, bộ bảo mật AiProtection, cổng 2.5G kép, tối ưu hóa độ trễ thấp và khả năng tương thích AiMesh để mở rộng phạm vi phủ sóng.",
    "Huawei AX3 Quad-Core" => "Bộ định tuyến Wi-Fi 6 nhỏ gọn có kiến trúc bộ xử lý lõi tứ, kết nối không dây băng tần kép, hỗ trợ HarmonyOS Mesh+, ghép nối một chạm NFC, cổng Gigabit và tối ưu hóa tín hiệu không dây mạnh mẽ cho gia đình và căn hộ.",
    "Linksys MR7350" => "Bộ định tuyến băng tần kép Wi-Fi 6 đáng tin cậy được thiết kế để kết nối mạng gia đình và thiết bị thông minh. Có tốc độ không dây AX1800, hỗ trợ mở rộng lưới, QoS thông minh, kiểm soát của phụ huynh, cổng Gigabit Ethernet và hiệu suất đa thiết bị ổn định cho các hộ gia đình hiện đại.",
    "Corsair RM750x" => "Bộ nguồn mô-đun hoàn toàn 750W cao cấp được thiết kế cho máy tính chơi game và máy trạm chuyên nghiệp. Có chứng nhận hiệu quả 80 Plus Gold, thiết kế cáp mô-đun hoàn toàn, quạt 135mm có độ ồn cực thấp, tụ điện Nhật Bản, chế độ quạt Zero RPM, khả năng tương thích ATX và cung cấp năng lượng đáng tin cậy cho các hệ thống chơi game hiệu suất cao.",
    "Cooler Master MWE Gold 750 V2" => "Bộ nguồn chơi game được sử dụng rộng rãi cung cấp công suất 750W, chứng nhận 80 Plus Gold, chuyển đổi nguồn DC-to-DC, quạt làm mát yên tĩnh, cáp mô-đun hoàn toàn và hiệu quả ổn định cho PC chơi game và năng suất. Thích hợp cho các hệ thống card đồ họa NVIDIA và AMD hiện đại.",
    "ASUS ROG Strix 850G" => "PSU chơi game cao cấp được thiết kế cho các bản dựng PC đam mê. Có công suất 850W, hiệu suất 80 Plus Gold, cáp mô-đun hoàn toàn, tản nhiệt cao cấp, quạt làm mát công nghệ hướng trục, tụ điện Nhật Bản và hoạt động ít tiếng ồn được tối ưu hóa cho các hệ thống chơi game và sáng tạo.",
    "MSI MAG A650BN" => "Bộ nguồn thân thiện với ngân sách phổ biến được thiết kế cho các hệ thống máy tính để bàn văn phòng và chơi game chính thống. Có công suất 650W, chứng nhận 80 Plus Bronze, thiết kế PFC chủ động, quạt làm mát yên tĩnh, điều chỉnh điện áp ổn định và hiệu suất đáng tin cậy cho các bản dựng PC cấp thấp và tầm trung.",
    "Seasonic Focus GX-750" => "PSU cao cấp được đánh giá cao trên toàn cầu với công suất 750W, chứng nhận 80 Plus Gold, cáp mô-đun hoàn toàn, điều khiển quạt im lặng lai, thiết kế ATX nhỏ gọn và độ tin cậy lâu dài vượt trội cho máy tính chơi game và máy trạm.",
    "Corsair CV650" => "Bộ nguồn máy tính để bàn giá cả phải chăng và đáng tin cậy được thiết kế cho các hệ thống văn phòng và PC chơi game cấp thấp. Có công suất 650W, hiệu suất 80 Plus Bronze, quạt làm mát tiếng ồn thấp 120mm, cung cấp năng lượng liên tục và khả năng tương thích với các thành phần máy tính để bàn hiện đại.",
    "Gigabyte UD750GM" => "Bộ nguồn chơi game hoàn toàn theo mô-đun có công suất 750W, hiệu suất 80 Plus Gold, tụ điện Nhật Bản chất lượng cao, quạt ổ trục thủy lực thông minh, thiết kế nhỏ gọn và đầu ra hiệu suất cao ổn định cho hệ thống chơi game và phát trực tuyến.",
    "Thermaltake Toughpower GF A3 850W" => "Bộ nguồn tương thích ATX 3.0 hiện đại được thiết kế cho phần cứng chơi game thế hệ tiếp theo. Có công suất 850W, hiệu suất 80 Plus Gold, hỗ trợ PCIe Gen 5, thiết kế mô-đun hoàn toàn, hệ thống làm mát cực kỳ yên tĩnh và khả năng tương thích mạnh mẽ với card đồ họa RTX 40-series.",
    "DeepCool PK650D" => "PSU định hướng ngân sách đáng tin cậy cung cấp công suất 650W, hiệu suất 80 Plus Bronze, các thành phần bên trong bền, PFC hoạt động, điều chỉnh điện áp ổn định và hiệu suất quạt yên tĩnh cho hệ thống máy tính để bàn văn phòng và chơi game.",
    "EVGA SuperNOVA 850 G6" => "PSU mô-đun hoàn toàn đẳng cấp dành cho người đam mê có công suất đầu ra 850W, chứng nhận 80 Plus Gold, quạt hoạt động im lặng ở chế độ sinh thái, thiết kế nhỏ gọn, tụ điện cao cấp của Nhật Bản và hiệu quả cao cho máy trạm chơi game và máy tính để bàn cao cấp.",
    "Logitech G Pro X TKL Lightspeed" => "Bàn phím chơi game thể thao điện tử chuyên nghiệp được thiết kế cho các game thủ và streamer cạnh tranh. Có kết nối LIGHTSPEED không dây, bố cục không cần phím, ánh sáng RGB LIGHTSYNC có thể tùy chỉnh, phím có thể lập trình, cấu hình bộ nhớ tích hợp, công tắc GX cơ học, điều khiển phương tiện và hiệu suất độ trễ cực thấp được tối ưu hóa cho chơi game thể thao điện tử.",
    "Razer Huntsman V2" => "Bàn phím chơi game cao cấp có Công tắc quang Razer để kích hoạt cực nhanh và độ trễ thấp. Bao gồm keycaps PBT doubleshot, đèn RGB Chroma, bọt giảm âm, tựa cổ tay từ tính, điều khiển phương tiện chuyên dụng và thăm dò USB tốc độ cao cho hiệu suất chơi game cạnh tranh.",
    "Corsair K100 RGB" => "Bàn phím chơi game cao cấp được thiết kế cho những người đam mê và game thủ chuyên nghiệp. Có công tắc cơ quang Corsair OPX, đèn RGB trên mỗi phím, điều khiển macro chuyên dụng, cấu trúc khung nhôm, công nghệ siêu thăm dò 8000Hz, tựa cổ tay có thể tháo rời và bánh xe điều khiển đa chức năng.",
    "Logitech MX Keys S" => "Bàn phím văn phòng cao cấp được sử dụng rộng rãi được thiết kế cho năng suất và quy trình làm việc chuyên nghiệp. Có công tắc cắt kéo cấu hình thấp, đèn nền thông minh, kết nối Bluetooth đa thiết bị, sạc USB-C, trải nghiệm gõ yên tĩnh, thiết kế tiện dụng và khả năng tương thích với hệ thống Windows và macOS.",
    "Keychron K2 Wireless Mechanical Keyboard" => "Bàn phím cơ không dây phổ biến được sử dụng rộng rãi cho công việc văn phòng và chơi game thông thường. Có bố cục 75% nhỏ gọn, kết nối Bluetooth và có dây, tùy chọn công tắc có thể thay thế nóng, đèn nền RGB, khả năng tương thích macOS và Windows và thời lượng pin dài.",
    "SteelSeries Apex Pro TKL" => "Bàn phím chơi game tiên tiến có công tắc cơ học có thể điều chỉnh OmniPoint cho các điểm kích hoạt có thể tùy chỉnh. Bao gồm màn hình thông minh OLED, đèn RGB, khung nhôm cấp máy bay, truyền qua USB, phần tựa cổ tay có thể tháo rời và thiết kế không phím mười phím sẵn sàng cho giải đấu.",
    "ASUS ROG Azoth" => "Bàn phím chơi game kiểu tùy chỉnh cao cấp có màn hình OLED, thiết kế gắn miếng đệm, công tắc có thể thay thế nóng, kết nối ba chế độ, ánh sáng RGB, âm thanh gõ cao cấp, các lớp giảm chấn silicone và tùy chỉnh cấp độ người đam mê để chơi game và năng suất.",
    "Dell KB216 Multimedia Keyboard" => "Bàn phím văn phòng đáng tin cậy được sử dụng rộng rãi trong các doanh nghiệp, trường học và môi trường văn phòng trên toàn thế giới. Có bố cục kích thước đầy đủ, phím tắt đa phương tiện, kết nối USB, trải nghiệm gõ êm ái, công tắc màng bền và thiết kế năng suất hàng ngày tiện dụng.",
    "HyperX Alloy Origins Core" => "Bàn phím chơi game không phím nhỏ gọn có công tắc cơ học HyperX, thân máy hoàn toàn bằng nhôm cấp máy bay, tùy chỉnh ánh sáng RGB, cáp USB-C có thể tháo rời, hỗ trợ chống bóng mờ và độ bền mạnh mẽ cho môi trường chơi game cạnh tranh.",
    "Logitech G213 Prodigy" => "Bàn phím chơi game giá cả phải chăng có vùng RGB LIGHTSYNC, cấu trúc chống tràn, phần tựa tay tích hợp, điều khiển phương tiện chuyên dụng, các phím chơi game màng được điều chỉnh để phản hồi và bố cục kích thước đầy đủ thoải mái để chơi game và sử dụng hàng ngày.",
    "Logitech G Pro X Superlight 2" => "Chuột chơi game thể thao điện tử chuyên nghiệp được thiết kế để mang lại hiệu suất cạnh tranh siêu nhẹ. Có cảm biến quang học HERO 2, lên đến 32.000 DPI, kết nối không dây LIGHTSPEED, hỗ trợ thăm dò 4K/8K, thiết kế siêu nhẹ 60g, sạc USB-C, chân PTFE và công nghệ không dây có độ trễ thấp tiên tiến được các vận động viên thể thao điện tử chuyên nghiệp trên toàn thế giới tin tưởng.",
    "Razer Viper V3 Pro" => "Chuột chơi game thể thao điện tử không dây cao cấp có cảm biến quang học Focus Pro 35K, thiết kế công thái học siêu nhẹ, công nghệ không dây HyperSpeed, công tắc chuột quang Gen-3, tốc độ bỏ phiếu lên đến 8000Hz, thời lượng pin dài và độ chính xác chơi game FPS cấp độ chuyên nghiệp.",
    "Logitech G502 X Lightspeed" => "Một trong những con chuột chơi game được công nhận nhất thế giới có công tắc quang-cơ lai LIGHTFORCE, cảm biến HERO 25K, cài đặt DPI có thể tùy chỉnh, thiết kế tiện dụng, kết nối LIGHTSPEED không dây, các nút có thể lập trình, hỗ trợ RGB và tính linh hoạt chơi game đa thể loại.",
    "Logitech MX Master 3S" => "Chuột văn phòng và năng suất cao cấp được thiết kế cho quy trình làm việc chuyên nghiệp và đa nhiệm. Có thiết kế điêu khắc tiện dụng, cuộn điện từ MagSpeed, nhấp chuột im lặng, cảm biến Darkfield 8000 DPI, sạc nhanh USB-C, kết nối đa thiết bị Bluetooth và khả năng tương thích với hệ thống Windows và macOS.",
    "Razer DeathAdder V3 Pro" => "Chuột chơi game công thái học nhẹ có cảm biến quang học Focus Pro 30K, công tắc quang học Gen-3, công nghệ HyperSpeed không dây, thiết kế siêu nhẹ, hình dạng thuận tay phải tiện dụng và độ chính xác theo dõi cấp thể thao điện tử để chơi game FPS và MOBA.",
    "Logitech M720 Triathlon" => "Chuột văn phòng không dây phổ biến được thiết kế cho năng suất và quy trình làm việc đa thiết bị. Có kết nối không dây Bluetooth và USB, các nút có thể lập trình, tiện nghi về mặt công thái học, chuyển đổi đa thiết bị, thời lượng pin dài, cuộn chính xác và hiệu suất văn phòng đáng tin cậy.",
    "SteelSeries Rival 3 Wireless" => "Chuột chơi game giá cả phải chăng có cảm biến quang học TrueMove Air, kết nối không dây kép, hiệu suất chơi game có độ trễ thấp, kết cấu nhẹ, ánh sáng RGB, thời lượng pin dài và công tắc bền phù hợp để chơi game và sử dụng máy tính để bàn hàng ngày.",
    "ASUS TUF Gaming M4 Wireless" => "Chuột chơi game không dây bền bỉ được thiết kế cho hiệu suất chơi game cạnh tranh. Có cảm biến quang học 12.000 DPI, thiết kế thuận cả hai tay nhẹ, các nút có thể lập trình, kết nối không dây và Bluetooth, hỗ trợ ASUS Aura Sync RGB và độ bền lấy cảm hứng từ quân đội.",
    "Corsair Ironclaw RGB Wireless" => "Chuột chơi game tiện dụng được thiết kế cho người chơi FPS và MOBA. Có cảm biến quang học 18.000 DPI, công nghệ Slipstream không dây, vùng chiếu sáng RGB, các nút có thể lập trình, công tắc Omron bền, bề mặt tay cầm có kết cấu và thiết kế tiện dụng bằng tay lớn thoải mái.",
    "Microsoft Bluetooth Ergonomic Mouse" => "Chuột không dây công thái học tập trung vào văn phòng được thiết kế cho các phiên làm việc lâu dài và môi trường làm việc chuyên nghiệp. Có kết nối Bluetooth, phần tựa ngón tay cái tiện dụng, cảm biến theo dõi mượt mà, thiết kế nhẹ tập trung vào sự thoải mái, khả năng tương thích đa nền tảng và hiệu quả pin lâu dài.",
    "NVIDIA GeForce RTX 4060" => "Card đồ họa chơi game chính thống được mua rộng rãi được thiết kế để chơi game mượt mà 1080p và 1440p cấp thấp. Có kiến trúc NVIDIA Ada Lovelace, bộ nhớ 8GB GDDR6, tạo khung hình DLSS 3 AI, hỗ trợ dò tia, giao diện PCIe 4.0, đầu ra HDMI 2.1 và DisplayPort 1.4a, tiêu thụ điện năng 115W thấp và hiệu quả tuyệt vời cho PC chơi game và sáng tạo nội dung.",
    "NVIDIA GeForce RTX 4070 SUPER" => "GPU chơi game hiệu năng cao được tối ưu hóa cho khối lượng công việc chơi game và người sáng tạo siêu 1440p. Có bộ nhớ GDDR12X 6GB, kiến trúc Ada Lovelace, hỗ trợ DLSS 3, lõi dò tia tiên tiến, giao diện PCIe 4.0, hỗ trợ mã hóa AV1, số lượng lõi CUDA cao và hiệu suất tản nhiệt hiệu quả cho PC chơi game đam mê.",
    "NVIDIA GeForce RTX 4080 SUPER" => "Card đồ họa đẳng cấp dành cho người đam mê được thiết kế để chơi game 1440p và 4K tốc độ làm mới cao. Có bộ nhớ GDDR16X 6GB, kiến trúc Ada Lovelace tiên tiến, thế hệ DLSS 3 khung hình, hiệu suất dò tia cao cấp, kết xuất tăng cường AI, kết nối PCIe 4.0 và các giải pháp tản nhiệt mạnh mẽ từ các thương hiệu hàng đầu như ASUS, MSI và Gigabyte.",
    "NVIDIA GeForce RTX 3060" => "Card đồ họa tầm trung cực kỳ phổ biến được sử dụng rộng rãi cho các hệ thống chơi game, phát trực tuyến và năng suất. Có kiến trúc Ampere, bộ nhớ GDDR12 6GB, hỗ trợ dò tia, nâng cấp DLSS AI, hỗ trợ PCIe 4.0, kết nối HDMI 2.1 và hiệu suất chơi game 1080p đáng tin cậy với giá trị đồng tiền bát gạo.",
    "NVIDIA GeForce RTX 4090" => "Card đồ họa NVIDIA hàng đầu được thiết kế để chơi game 4K cực cao, khối lượng công việc AI, kết xuất chuyên nghiệp và hệ thống máy trạm cao cấp. Có bộ nhớ GDDR24X 6GB, kiến trúc Ada Lovelace, lõi dò tia tiên tiến, công nghệ DLSS 3, số lượng lõi CUDA khổng lồ, giao diện PCIe 4.0 và hiệu suất tăng tốc AI và chơi game hàng đầu trong ngành."
];

$count = 0;
$notFound = [];

DB::beginTransaction();
try {
    foreach ($data as $title => $desc) {
        $product = DB::table('product')->where('title', trim($title))->first();
        if (!$product) {
            $product = DB::table('product')->where('title', 'like', trim($title) . '%')->first();
        }
        
        if ($product) {
            $htmlDesc = "<p>" . $desc . "</p>";
            // Update product table
            DB::table('product')
                ->where('id', $product->id)
                ->update([
                    'description' => $desc,
                    'content' => $htmlDesc,
                    'updated_at' => now()
                ]);
                
            // Update product_translations table
            DB::table('product_translations')
                ->where('product_id', $product->id)
                ->where('lang', 'vi')
                ->update([
                    'description' => $desc,
                    'content' => $htmlDesc,
                    'updated_at' => now()
                ]);
                
            $count++;
            echo "Updated description & content for ID {$product->id}: {$product->title}\n";
        } else {
            $notFound[] = $title;
        }
    }
    DB::commit();
    echo "\nSUCCESS: Updated descriptions for $count products.\n";
    if (!empty($notFound)) {
        echo "Not found (" . count($notFound) . "): " . implode(', ', $notFound) . "\n";
    }
} catch (\Exception $e) {
    DB::rollBack();
    echo "ERROR: " . $e->getMessage() . "\n";
}
